/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(home)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/cadastro` | `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/contato` | `/contato`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/productListScreen` | `/productListScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/produtoCard` | `/produtoCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/layout`; params?: Router.UnknownInputParams; } | { pathname: `/components/menu`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(home)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/cadastro` | `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/contato` | `/contato`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/productListScreen` | `/productListScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/produtoCard` | `/produtoCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/components/menu`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(home)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/cadastro${`?${string}` | `#${string}` | ''}` | `/cadastro${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/contato${`?${string}` | `#${string}` | ''}` | `/contato${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/productListScreen${`?${string}` | `#${string}` | ''}` | `/productListScreen${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/produtoCard${`?${string}` | `#${string}` | ''}` | `/produtoCard${`?${string}` | `#${string}` | ''}` | `/components/layout${`?${string}` | `#${string}` | ''}` | `/components/menu${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(home)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/cadastro` | `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/contato` | `/contato`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/productListScreen` | `/productListScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/produtoCard` | `/produtoCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/layout`; params?: Router.UnknownInputParams; } | { pathname: `/components/menu`; params?: Router.UnknownInputParams; };
    }
  }
}
